compatibility_date = "2023-05-10"

main = "./dist/worker.js"

[api]
# Replace with your Cloudflare account email
email = "mm@horizon.io"

# Replace with your Cloudflare API key
key = "3600a71abf91255a8ff77c39d336dea75b43e"

[experimental]
output_module = true

[build]
command = "npm run build" 